# Non-Secure side configuration for the trustzone_ns sample.

CONFIG_ARM_NONSECURE_FIRMWARE=y

# Link against the veneer library produced by the Secure build.
CONFIG_ARM_FIRMWARE_USES_SECURE_ENTRY_FUNCS=y

# Use per-entry-function mutex instead of scheduler-wide lock.
CONFIG_ARM_TZ_ENTRY_MUTEX=y

# Enable k_thread_join
CONFIG_THREAD_MONITOR=y

CONFIG_PRINTK=y
